# Generated by Django 2.2.4 on 2020-01-27 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('oily', models.CharField(choices=[('O', '유익함'), ('', '영향없음'), ('X', '유해')], max_length=10)),
                ('dry', models.CharField(choices=[('O', '유익함'), ('', '영향없음'), ('X', '유해')], max_length=10)),
                ('sensitive', models.CharField(choices=[('O', '유익함'), ('', '영향없음'), ('X', '유해')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('ingredients', models.CharField(blank=True, max_length=254)),
                ('monthlySales', models.IntegerField()),
                ('oilyScore', models.IntegerField(blank=True, null=True)),
                ('dryScore', models.IntegerField(blank=True, null=True)),
                ('sensitiveScore', models.IntegerField(blank=True, null=True)),
                ('connect_ingre', models.ManyToManyField(blank=True, related_name='ingre_list', through='item.Connect', to='item.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='connect',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Ingredient'),
        ),
        migrations.AddField(
            model_name='connect',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Product'),
        ),
    ]
