# Generated by Django 2.2.4 on 2020-01-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imageId',
            new_name='imageUrl',
        ),
    ]
